In [3]:
import numpy as np
from sklearn.metrics import accuracy_score, confusion_matrix, roc_auc_score, roc_curve

n = 10000

ratio = 0.95

n_0 = int((1 - ratio) * n)
n_1 = int((ratio*n))

y = np.array([0]*n_0 + [1]*n_1)

print(y)

[0 0 0 ... 1 1 1]


In [6]:
y_proba = np.array([1] * n)
y_pred = y_proba > 0.5

print(y_pred)

[ True  True  True ...  True  True  True]


In [11]:
print(f"Accuracy score: {accuracy_score(y, y_pred)}")
cf_mat = confusion_matrix(y, y_pred)
print("Confusion matrix")
print(cf_mat)

print(f"Class 0 accuracy: {cf_mat[0][0]/ n_0}")
print(f"Class 1 accuracy: {cf_mat[1][1]/ n_1}")

Accuracy score: 0.95
Confusion matrix
[[   0  500]
 [   0 9500]]
Class 0 accuracy: 0.0
Class 1 accuracy: 1.0


In [18]:
y_proba_2 = np.array(np.random.uniform(0, 0.7, n_0).tolist() + np.random.uniform(0.3, 1.0, n_1).tolist())

y_pred_2 = y_proba_2 > 0.5

print(f"Accuracy Score: {accuracy_score(y, y_pred_2)}")
cf_mat = confusion_matrix(y, y_pred_2)
print("Confusion Matrix")
print(cf_mat)

print(f"Class 0 accuracy: {cf_mat[0][0] / n_0}")
print(f"Class 1 accuracy: {cf_mat[1][1] / n_1}")

Accuracy Score: 0.7167
Confusion Matrix
[[ 358  142]
 [2691 6809]]
Class 0 accuracy: 0.716
Class 1 accuracy: 0.7167368421052631


In [19]:
import matplotlib.pyplot as plt

def plot_roc_curve(true_y, y_prob):
    
    '''plot the roc curve based on the probabilities'''
    
    fpr, tpr, thresholds = roc_curve(true_y, y_prob)
    
    plt.plot(fpr, tpr)
    plt.xlabel("False Positive rate")
    plt.ylabel("True positive rate")