Name: Aman Kumar <br>
Hawk Id: A20538809 <br>
CS 512 (Computer Vision) <br>
Fall'24

**Part A: Vector Operations**
Let, p = [2,-1,4], q = [0,3,5], r = [1,-2,2]

**Find:**
1. 3p+2q

In [76]:
#Solution:
import numpy as np
import math

In [3]:
#Solution Part A: 1
p = np.array([2, -1, 4])
q = np.array([0, 3, 5])
r = np.array([1, -2, 2])

result = 3*p + 2*q
result

array([ 6,  3, 22])

2. ^p: a unit vector in the direction of p

In [4]:
#Solution
magnitude_p = np.linalg.norm(p)
unit_vector_p = p/magnitude_p
unit_vector_p

array([ 0.43643578, -0.21821789,  0.87287156])

3. ||p|| and the angle of p relative to the positive y-axis

In [5]:
#Solution:
magnitude_p = np.linalg.norm(p)
angle_wrt_yAxis = np.arccos(p[1]/magnitude_p)
angle_in_degrees = np.degrees(angle_wrt_yAxis)
print(angle_in_degrees)

102.60438264837919


4. The direction cosines of p

In [6]:
#Solution:
direction_cosines_p = p/magnitude_p
direction_cosines_p

array([ 0.43643578, -0.21821789,  0.87287156])

5. The angle between p and q

In [7]:
#Solution:
dot_product_pq = np.dot(p,q)
magnitude_q = np.linalg.norm(q)
cosine_angle_pq = dot_product_pq/(magnitude_p*magnitude_q)
angle_between_pq = np.arccos(cosine_angle_pq)
angle_between_pq_degrees = np.degrees(angle_between_pq)
angle_between_pq_degrees

50.490287713806076

6. p ⋅q and q ⋅ p

In [8]:
#Solution:
p_dot_q = np.dot(p,q)
print(p_dot_q)
q_dot_p = np.dot(q,p)
print(q_dot_p)
print("As Dot product is commutative")

17
17
As Dot product is commutative


7. p⋅q using the angle between p and q

In [9]:
#Solution:
p_dot_q_usingAngle = magnitude_p*magnitude_q*np.cos(angle_between_pq)
print(p_dot_q_usingAngle)

17.0


8. The scalar projection of q onto p

In [10]:
#Solution:
scalar_proj_q_onto_p = np.dot(p,q)/magnitude_p
scalar_proj_q_onto_p

3.709704134011871

9. A vector that is perpendicular to p

In [11]:
#Solution:
perpendicular_to_p = np.cross(p, np.array([1,0,0]))
perpendicular_to_p

array([0, 4, 1])

10. pxq and qxp

In [12]:
#Solution:
pxq = np.cross(p,q)
qxp = np.cross(q,p)

print(f"pxq is {pxq}")
print(f"qxp is {qxp}")

pxq is [-17 -10   6]
qxp is [17 10 -6]



11. A vector that is perpendicular to both p and q

In [13]:
#Solution:
perpendicular_to_p_q = np.cross(p,q)
perpendicular_to_p_q

array([-17, -10,   6])

12. The linear dependency between p, q, and r

In [14]:
#Solution:
matrix = np.column_stack((p,q,r))
rank = np.linalg.matrix_rank(matrix)

if rank < 3:
  print("p, q, r are linearly dependent")
else:
  print("p, q, r are linearly independent")

p, q, r are linearly independent


13. p(transpose)q and pq(transpose)

In [15]:
#Solution:
p_transpose_q = np.dot(p.T, q)
print(p_transpose_q)

p_q_transpose = np.dot(p, q.T)
print(p_q_transpose)

17
17


**Part B: Matrix Operations**

In [16]:
x = np.array([[2,1,0],[-1,3,4],[3,2,-2]])
y = np.array([[4,-1,2],[3,0,-3],[1,2,1]])
z = np.array([[2,0,-1],[1,4,5],[3,1,2]])
s = np.array([[-1],[4],[0]])

**Find:**
  1. X+2Y

In [17]:
#Solution:
x_plus_2y = x + 2*y
x_plus_2y

array([[10, -1,  4],
       [ 5,  3, -2],
       [ 5,  6,  0]])

2. XY and YX

In [18]:
#Solution
x_y = np.dot(x,y)
y_x = np.dot(y,x)
print(x_y)
print(y_x)

[[11 -2  1]
 [ 9  9 -7]
 [16 -7 -2]]
[[15  5 -8]
 [-3 -3  6]
 [ 3  9  6]]


3. (XY)^T and Y^T.X^t

In [19]:
#Solution:
xy_T = x_y.T
print(xy_T)

yT_xT = np.dot(y.T, x.T)
print(yT_xT)

[[11  9 16]
 [-2  9 -7]
 [ 1 -7 -2]]
[[11  9 16]
 [-2  9 -7]
 [ 1 -7 -2]]


4. X|andZ|(see question A-12)

In [20]:
#Solution:
def check_linear_dependency(A, B):
    try:
        for i in range(A.shape[1]):
            solution, residuals, rank, s = np.linalg.lstsq(B, A[:, i], rcond=None)
            if not np.allclose(np.dot(B, solution), A[:, i]):
                return False
        return True
    except np.linalg.LinAlgError:
        return False

linear_dependency_XZ = check_linear_dependency(x, z)
linear_dependency_ZX = check_linear_dependency(z, x)

print("Linear dependency between columns of X and Z:")
print(f"   X columns are dependent on Z columns: {linear_dependency_XZ}")
print(f"   Z columns are dependent on X columns: {linear_dependency_ZX}")

Linear dependency between columns of X and Z:
   X columns are dependent on Z columns: True
   Z columns are dependent on X columns: True


5 The matrix (either X, Y, or Z) in which the row vectors form an orthogonal set

In [26]:
#Solution:
def is_orthogonal(matrix):
    for i in range(matrix.shape[0]):
        for j in range(i + 1, matrix.shape[0]):
            if not np.isclose(np.dot(matrix[i], matrix[j]), 0):
                return False
    return True

In [27]:
orthogonal_matrix = None
if is_orthogonal(x):
    orthogonal_matrix = "x"
elif is_orthogonal(y):
    orthogonal_matrix = "y"
elif is_orthogonal(z):
    orthogonal_matrix = "z"

print(f"5. Matrix with orthogonal row vectors: {orthogonal_matrix}")

5. Matrix with orthogonal row vectors: None


6. X' and Y' (see question B-5)

In [32]:
#Solution:
inv_x = np.linalg.inv(x)
inv_y = np.linalg.inv(y)

print(f"Inverse of x is {inv_x}")
print(f"Inverse of y is {inv_y}")

Inverse of x is [[ 0.77777778 -0.11111111 -0.22222222]
 [-0.55555556  0.22222222  0.44444444]
 [ 0.61111111  0.05555556 -0.38888889]]
Inverse of y is [[ 0.14285714  0.11904762  0.07142857]
 [-0.14285714  0.04761905  0.42857143]
 [ 0.14285714 -0.21428571  0.07142857]]


7. inv(Z) (see question B-4)

In [33]:
inv_z = np.linalg.inv(z)
inv_z

array([[ 0.17647059, -0.05882353,  0.23529412],
       [ 0.76470588,  0.41176471, -0.64705882],
       [-0.64705882, -0.11764706,  0.47058824]])

8. The product Xs

In [34]:
x_s = np.dot(x,s)
x_s

array([[ 2],
       [13],
       [ 5]])

9. The scalar projection of the rows of X onto the vector s (with s normalized)

In [35]:
#Solution:
s_magnitude = np.linalg.norm(s)
s_normalised = s/s_magnitude

scalar_projections_x_onto_s_norm = np.dot(x, s_normalised)
scalar_projections_x_onto_s_norm

array([[0.48507125],
       [3.15296313],
       [1.21267813]])

10. The vector projection of the rows of X onto the vector s (with s normalized)

In [36]:
#Solution:
vector_projection_x_onto_s_norm = scalar_projections_x_onto_s_norm[:, np.newaxis]* s_normalised.T
vector_projection_x_onto_s_norm

array([[[-0.11764706,  0.47058824,  0.        ]],

       [[-0.76470588,  3.05882353,  0.        ]],

       [[-0.29411765,  1.17647059,  0.        ]]])

11. The linear combination of the columns of X using the elements of s



In [37]:
#Solution:
linear_combination_x_s = np.dot(x,s)
linear_combination_x_s

array([[ 2],
       [13],
       [ 5]])

12. The solution t for the equation Yt = s

In [42]:
#Solution:
# Step 1: Compute the transpose of Y
Y_T = y.T

# Step 2: Compute Y^T Y
Y_T_Y = np.dot(Y_T, y)

# Step 3: Compute the inverse of Y^T Y
Y_T_Y_inv = np.linalg.inv(Y_T_Y)

# Step 4: Compute Y^T s
Y_T_s = np.dot(Y_T, s)

# Step 5: Compute the solution t
t = np.dot(Y_T_Y_inv, Y_T_s)

t

array([[ 0.33333333],
       [ 0.33333333],
       [-1.        ]])

13. The solution t for the equation Z t = s and the reason for it (see question B-7)

In [44]:
#Solution:
# Step 1: Compute the transpose of Z
Z_T = z.T

# Step 2: Compute Z^T Z
Z_T_Z = np.dot(Z_T, z)

# Step 3: Compute the inverse of Z^T Z
Z_T_Z_inv = np.linalg.inv(Z_T_Z)

# Step 4: Compute Z^T s
Z_T_s = np.dot(Z_T, s)

# Step 5: Compute the solution t
t = np.dot(Z_T_Z_inv, Z_T_s)
t

array([[-0.41176471],
       [ 0.88235294],
       [ 0.17647059]])

**Part C: Eigenvalues and Eigenvectors**

In [45]:
m = np.array([[3,2],[-1,4]])
n = np.array([[5,-3],[-3,6]])
p = np.array([[2,4],[4,8]])

Find: <br>
1. The eigenvalues and corresponding eigenvectors of M

In [46]:
#Solution:
eigenvalues, eigenvectors = np.linalg.eig(m)

print(f"eigen values of m are : {eigenvalues}")
print(f"eigen vectors of m are : {eigenvectors}")

eigen values of m are : [3.5+1.32287566j 3.5-1.32287566j]
eigen vectors of m are : [[0.81649658+0.j         0.81649658-0.j        ]
 [0.20412415+0.54006172j 0.20412415-0.54006172j]]


2. The dot product between the eigenvectors of M

In [47]:
#Solution:
dot_product_eigen_vector_m = np.dot(eigenvectors[:, 0], eigenvectors[:, 1])
dot_product_eigen_vector_m

(1.0000000000000002+0j)

3. The dot product between the eigenvectors of N

In [52]:
#Solution:
eigenvalues_n, eigenvectors_n = np.linalg.eig(n)

print(eigenvectors_n)

dot_product_eigen_vector_n = np.dot(eigenvectors_n[:,0], eigenvectors_n[:,1])

dot_product_eigen_vector_n

[[-0.76301998  0.6463749 ]
 [-0.6463749  -0.76301998]]


0.0

4. The property of the eigenvectors of N and the reason for it (see question C-4)

In [57]:
#Solution:
print(eigenvectors_n)

print(f"dot product of eigen vectors of n is {eigenvectors_n}")

print("Dot product of eigen values of n is close to 0 so the eigen vectors of n are orthogonal")

[[-0.76301998  0.6463749 ]
 [-0.6463749  -0.76301998]]
dot product of eigen vectors of n is [[-0.76301998  0.6463749 ]
 [-0.6463749  -0.76301998]]
Dot product of eigen values of n is close to 0 so the eigen vectors of n are orthogonal


5. The value of a trivial solution t to the equation Pt = 0

In [61]:
#Solution:
t = np.array([0,0])

print(f"Trivial solution to Pt = 0: {t}")

Trivial solution to Pt = 0: [0 0]


6. The value of two non-trivial solutions t to the equation Pt =0

In [71]:
from scipy.linalg import svd

U, S, Vt = svd(p)


non_zero_singular_values = S > 1e-10


null_space_vectors = Vt.T[:, ~non_zero_singular_values]


print("Non-trivial solutions to Pt = 0 (before scaling):")
print(null_space_vectors)


scaling_factor = 2 / np.linalg.norm(null_space_vectors)
scaled_solutions = null_space_vectors * scaling_factor

print("Scaled non-trivial solutions to Pt = 0:")
print(scaled_solutions)

Non-trivial solutions to Pt = 0 (before scaling):
[[-0.89442719]
 [ 0.4472136 ]]
Scaled non-trivial solutions to Pt = 0:
[[-1.78885438]
 [ 0.89442719]]


7. The only solution t to the equation M t = 0 and the reason for having a single solution

In [72]:
U, S, Vt = svd(m)

# Find null space vectors corresponding to zero singular values
null_space_vectors = Vt.T[:, np.isclose(S, 0)]

print("Solution to Mt = 0:")
print(null_space_vectors)

Solution to Mt = 0:
[]


**Part D: Neural Networks Basics** <br>
.1 Given a neuron with input values x, =05., x2= - 0.8, and x3=0.3, weights w,=0.4, w=, - 0.6, and w3=0.9, and a bias b=0.2, compute the output of the neuron before applying any activation function.

In [73]:
x1, x2, x3 = 0.5, -0.8, 0.3
w1, w2, w3 = 0.4, -0.6, 0.9
b = 0.2


In [75]:
#output of the neuron before applying any activation function.
output = x1*w1 + x2*w2 + x3*w3 + b
print(f"output of the neuron before applying any activation function is : {output}")

output of the neuron before applying any activation function is : 1.15


2. Using the output computed ni the previous question, apply the sigmoid activation function to find the activation value.

In [77]:
sigmoid = 1 / (1 + math.exp(-output))

print(f"activation value is : {sigmoid}")

activation value is : 0.759510916949111


3. Given the same input values and weights as ni question 1, compute the output of the neuron after applying a ReLU activation function.

In [78]:
relu = max(0, output)

print(f"output (relu): {relu}")

output (relu): 1.15


4. Given a neural network layer with weights Wi bias bh, and input x, as follows: <br>
compute the output of the layer using ReLU activation.

In [80]:
#Solution:
w = np.array([[0.4, 0.3],[0.2, 0.7]])
b = np.array([[0.1],[-0.1]])
x = np.array([[1],[2]])

In [81]:
z = np.dot(w,x) + b

relu_output = np.maximum(0,z)

print(f"output of layer using ReLU activation is : {relu_output}")

output of layer using ReLU activation is : [[1.1]
 [1.5]]


5. Feed the output of the layer from the previous question into an output layer with weights W., bias bo, as folows:<br>
w.=|0.5 - 0.3),b.=|0.1)<br>
compute the output of the layer using sigmoid activation.

In [85]:
#Solution:
w_out = np.array([0.5, -0.3])
b_out = np.array([0.1])
z_output = np.dot(w_out, z) + b_out

sigmoid_out = 1/(1 + np.exp(-z_output))

print(f"output of the layer using sigmoid activation: {sigmoid_out}")

output of the layer using sigmoid activation: [0.549834]
