<a href="https://colab.research.google.com/github/amansingh202/Machine-Learning/blob/main/Computer_Vision/Cv_AS0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Name: Aman Kumar <br>
Hawk Id: A20538809 <br>
CS 512 (Computer Vision)

**Part A: Vector Operations**
Let, p = [2,-1,4], q = [0,3,5], r = [1,-2,2]

**Find:**
1. 3p+2q

In [1]:
#Solution:
import numpy as np

In [4]:
#Solution Part A: 1
p = np.array([2, -1, 4])
q = np.array([0, 3, 5])

result = 3*p + 2*q
result

array([ 6,  3, 22])

1. ^p: a unit vector in the direction of p

In [6]:
#Solution
magnitude_p = np.linalg.norm(p)
unit_vector_p = p/magnitude_p
unit_vector_p

array([ 0.43643578, -0.21821789,  0.87287156])

2. ||p|| and the angle of p relative to the positive y-axis

In [10]:
#Solution:
magnitude_p = np.linalg.norm(p)
angle_wrt_yAxis = np.arccos(p[1]/magnitude_p)
angle_in_degrees = np.degrees(angle_wrt_yAxis)
print(angle_in_degrees)

102.60438264837919


3. The direction cosines of p

In [11]:
#Solution:
direction_cosines_p = p/magnitude_p
direction_cosines_p

array([ 0.43643578, -0.21821789,  0.87287156])

4. The angle between p and q

In [14]:
#Solution:
dot_product_pq = np.dot(p,q)
magnitude_q = np.linalg.norm(q)
cosine_angle_pq = dot_product_pq/(magnitude_p*magnitude_q)
angle_between_pq = np.arccos(cosine_angle_pq)
angle_between_pq_degrees = np.degrees(angle_between_pq)
angle_between_pq_degrees

50.490287713806076

5. p ⋅q and q ⋅ p

In [16]:
#Solution:
p_dot_q = np.dot(p,q)
print(p_dot_q)
q_dot_p = np.dot(q,p)
print(q_dot_p)
print("As Dot product is commutative")

17
17
As Dot product is commutative
