<a href="https://colab.research.google.com/github/amansingh202/Machine-Learning/blob/main/Computer_Vision/Cv_AS0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Name: Aman Kumar <br>
Hawk Id: A20538809 <br>
CS 512 (Computer Vision)

**Part A: Vector Operations**
Let, p = [2,-1,4], q = [0,3,5], r = [1,-2,2]

**Find:**
1. 3p+2q

In [2]:
#Solution:
import numpy as np

In [3]:
#Solution Part A: 1
p = np.array([2, -1, 4])
q = np.array([0, 3, 5])
r = np.array([1, -2, 2])

result = 3*p + 2*q
result

array([ 6,  3, 22])

2. ^p: a unit vector in the direction of p

In [4]:
#Solution
magnitude_p = np.linalg.norm(p)
unit_vector_p = p/magnitude_p
unit_vector_p

array([ 0.43643578, -0.21821789,  0.87287156])

3. ||p|| and the angle of p relative to the positive y-axis

In [5]:
#Solution:
magnitude_p = np.linalg.norm(p)
angle_wrt_yAxis = np.arccos(p[1]/magnitude_p)
angle_in_degrees = np.degrees(angle_wrt_yAxis)
print(angle_in_degrees)

102.60438264837919


4. The direction cosines of p

In [6]:
#Solution:
direction_cosines_p = p/magnitude_p
direction_cosines_p

array([ 0.43643578, -0.21821789,  0.87287156])

5. The angle between p and q

In [7]:
#Solution:
dot_product_pq = np.dot(p,q)
magnitude_q = np.linalg.norm(q)
cosine_angle_pq = dot_product_pq/(magnitude_p*magnitude_q)
angle_between_pq = np.arccos(cosine_angle_pq)
angle_between_pq_degrees = np.degrees(angle_between_pq)
angle_between_pq_degrees

50.490287713806076

6. p ⋅q and q ⋅ p

In [8]:
#Solution:
p_dot_q = np.dot(p,q)
print(p_dot_q)
q_dot_p = np.dot(q,p)
print(q_dot_p)
print("As Dot product is commutative")

17
17
As Dot product is commutative


7. p⋅q using the angle between p and q

In [9]:
#Solution:
p_dot_q_usingAngle = magnitude_p*magnitude_q*np.cos(angle_between_pq)
print(p_dot_q_usingAngle)

17.0


8. The scalar projection of q onto p

In [10]:
#Solution:
scalar_proj_q_onto_p = np.dot(p,q)/magnitude_p
scalar_proj_q_onto_p

3.709704134011871

9. A vector that is perpendicular to p

In [11]:
#Solution:
perpendicular_to_p = np.cross(p, np.array([1,0,0]))
perpendicular_to_p

array([0, 4, 1])

10. pxq and qxp

In [12]:
#Solution:
pxq = np.cross(p,q)
qxp = np.cross(q,p)

print(f"pxq is {pxq}")
print(f"qxp is {qxp}")

pxq is [-17 -10   6]
qxp is [17 10 -6]



11. A vector that is perpendicular to both p and q

In [13]:
#Solution:
perpendicular_to_p_q = np.cross(p,q)
perpendicular_to_p_q

array([-17, -10,   6])

12. The linear dependency between p, q, and r

In [14]:
#Solution:
matrix = np.column_stack((p,q,r))
rank = np.linalg.matrix_rank(matrix)

if rank < 3:
  print("p, q, r are linearly dependent")
else:
  print("p, q, r are linearly independent")

p, q, r are linearly independent


13. p(transpose)q and pq(transpose)

In [15]:
#Solution:
p_transpose_q = np.dot(p.T, q)
print(p_transpose_q)

p_q_transpose = np.dot(p, q.T)
print(p_q_transpose)

17
17


**Part B: Matrix Operations**

In [16]:
x = np.array([[2,1,0],[-1,3,4],[3,2,-2]])
y = np.array([[4,-1,2],[3,0,-3],[1,2,1]])
z = np.array([[2,0,-1],[1,4,5],[3,1,2]])
s = np.array([[-1],[4],[0]])

**Find:**
  1. X+2Y

In [17]:
#Solution:
x_plus_2y = x + 2*y
x_plus_2y

array([[10, -1,  4],
       [ 5,  3, -2],
       [ 5,  6,  0]])

2. XY and YX

In [18]:
#Solution
x_y = np.dot(x,y)
y_x = np.dot(y,x)
print(x_y)
print(y_x)

[[11 -2  1]
 [ 9  9 -7]
 [16 -7 -2]]
[[15  5 -8]
 [-3 -3  6]
 [ 3  9  6]]


3. (XY)^T and Y^T.X^t

In [19]:
#Solution:
xy_T = x_y.T
print(xy_T)

yT_xT = np.dot(y.T, x.T)
print(yT_xT)

[[11  9 16]
 [-2  9 -7]
 [ 1 -7 -2]]
[[11  9 16]
 [-2  9 -7]
 [ 1 -7 -2]]


4. X|andZ|(see question A-12)

In [20]:
#Solution:
def check_linear_dependency(A, B):
    try:
        for i in range(A.shape[1]):
            solution, residuals, rank, s = np.linalg.lstsq(B, A[:, i], rcond=None)
            if not np.allclose(np.dot(B, solution), A[:, i]):
                return False
        return True
    except np.linalg.LinAlgError:
        return False

linear_dependency_XZ = check_linear_dependency(x, z)
linear_dependency_ZX = check_linear_dependency(z, x)

print("Linear dependency between columns of X and Z:")
print(f"   X columns are dependent on Z columns: {linear_dependency_XZ}")
print(f"   Z columns are dependent on X columns: {linear_dependency_ZX}")

Linear dependency between columns of X and Z:
   X columns are dependent on Z columns: True
   Z columns are dependent on X columns: True
